version: "3.3"
services:
  frontend:
    container_name: frontend
    platform: linux/arm64/v8
    image: kirillkamratov/frontend-release:1.0.0
    restart:
      unless-stopped
    ports:
      - "8081:80"
  backend:
    container_name: backend
    platform: linux/arm64/v8
    image: kirillkamratov/backend-release:1.0.0
    networks:
      - backend-database
    restart: "unless-stopped"
    ports:
      - "4000:3001"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    container_name: postgres
    image: "postgres"
    env_file:
      - ./.env
    networks:
      - backend-database
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
volumes:
  pg_data:
    driver: local

networks:
  backend-database: {}
